name: CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test
        run: ./gradlew clean test --console=plain

      - name: Build with Gradle
        run: ./gradlew build -x test --console=plain

      # 1. AWS 인증
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 2.Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 3. Docker 이미지 빌드 & 푸시
      - name: Build docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG=sha-${{ github.sha }}

          docker build -t ${{ secrets.ECR_REPOSITORY }} .
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${IMAGE_URI}:latest
          docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${IMAGE_URI}:${IMAGE_TAG}

          docker push ${IMAGE_URI}:latest
          docker push ${IMAGE_URI}:${IMAGE_TAG}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: production
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev')
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Send SSM Command
        run: |
          aws ssm send-command \
            --region ${{ secrets.AWS_REGION }} \
            --document-name "AWS-RunShellScript" \
            --targets "Key=tag:Environment,Values=prod" "Key=tag:DeployTarget,Values=community-app" \
            --comment "Deploy Backend" \
            --parameters "commands=[\"cd /home/ubuntu/app\",\"AWS_REGION=${{ secrets.AWS_REGION }} AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }} sh deploy.sh latest\"]" \
            --output text

        
